name: Bug Report
description: Report a bug
labels: [bug]
body:
    - type: textarea
      attributes:
          label: Description
      validations:
          required: true
    - type: textarea
      attributes:
          label: Skyrim + Plugin version
          placeholder: Skyrim 1.7.104.0, SkyZoom 1.3
      validations:
          required: true
    - type: textarea
      attributes:
          label: SkyZoom logs
          description: SkyZoom.log file
          render: text
