name: Bug Report
description: Report a bug
labels: [bug]
body:
    - type: textarea
      attributes:
          label: Description
      validations:
          required: true
    - type: textarea
      attributes:
          label: Game + Mod Version
          placeholder: Skyrim 1.6.1170.0, SkyZoom 1.0
      validations:
          required: true
    - type: textarea
      attributes:
          label: SkyZoom logs
          description: SkyZoom.log file
          render: text
